# Generated by Django 3.2.6 on 2021-08-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_auto_20210821_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='mode',
            field=models.CharField(help_text='Data collection mode (for selecting analysis)', max_length=56),
        ),
    ]
